import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "../components/Providers";

const jakarta = Plus_Jakarta_Sans({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Patientrest",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Providers>
				<body
					className={cn(
						"min-h-screen dark font-[var(--font-sans)]",
						jakarta.className
					)}
				>
					<Navbar />
					{children}
				</body>
			</Providers>
		</html>
	);
}
